### ISSUE TITLE
Out of range

### ISSUE THREAD

**Issue by assemblu** [30350n/printable-instruments#2]
When I try to export these out to kicad, I get the error below. If you know what to do can you please let me know too? :)

> Traceback (most recent call last):
  File "export.py", line 750, in <module>
    _main()
  File "export.py", line 746, in _main
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 123, in run
    self.save_raw(self.effect())
  File "export.py", line 323, in effect
    self.processExportLayer()
  File "export.py", line 468, in processExportLayer
    kicad_edgecut_string = self.exportEdgeCut(kicad_mod = options.filetype == "kicad_module")
  File "export.py", line 659, in exportEdgeCut
    y = (path[1][1])
IndexError: list index out of range

**Comment by 30350n** [comment]
You need to set `Flatten Bezier` to `yes` in the export settings of svg2shenzhen.
(Check the recommended settings in the read me again, if you run into similar issues ^^)
